/** Central palette — confident navy with a warm academic accent. */
export const COLORS = {
  primary: '#3157D5',
  primaryDark: '#173278',
  primaryLight: '#8EA8FF',
  accent: '#F2B84B',
  background: '#F5F7FC',
  card: '#FFFFFF',
  textPrimary: '#14213D',
  textSecondary: '#5F6B85',
  textOnPrimary: '#FFFFFF',
  surface: '#E8EDFF',
  border: '#DDE3F0',
  shadow: '#182A5C',
  success: '#147D64',
  successSoft: '#DDF7EE',
  error: '#C63D4F',
  errorSoft: '#FCE8EB',
  modalSurface: '#090D18',
  modalSurfaceRaised: '#151B2B',
  modalBorder: '#2A344A',
  modalText: '#F7F9FF',
  modalTextSecondary: '#AAB4C8',
} as const;
